[Task 4] API Design & Framework. Create signin.
JuliaKholodetska/Task4-Full-Stack-JS-Internship pull request #5
Opened 2021-03-31 06:39 UTC by JuliaKholodetska

2021-04-01 07:35 UTC, MariiaKolisnyk requested changes

2021-04-01 07:35 UTC, MariiaKolisnyk commented on client/src/App.js
>  					<Route path="/cart/:id?" component={CartPage}></Route>
what is the question mark for?

2021-04-01 07:35 UTC, MariiaKolisnyk commented on client/src/pages/RegisterPage.js
> +						required
it would be nice to check whether input is email format

2021-04-01 07:35 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +				return;
`return res.send()` looks more common for me

2021-04-01 09:50 UTC, JuliaKholodetska commented on client/src/App.js
>  					<Route path="/cart/:id?" component={CartPage}></Route>
So that I can check products and change quantities in the cart without error.

2021-04-01 13:58 UTC, MariiaKolisnyk commented on client/src/App.js
>  					<Route path="/cart/:id?" component={CartPage}></Route>
I'm not familiar with React router parameters. could you please give me a link to docs or tutorial where it's described?

2021-04-01 14:19 UTC, MariiaKolisnyk requested changes

2021-04-01 14:19 UTC, MariiaKolisnyk commented on .gitignore
> +backend/utils.js
oh, I did not mean that. you just shouldn't use any default values here - `process.env.JWT_SECRET || "somethingsecret",` - just take the value from the env

2021-04-01 14:19 UTC, MariiaKolisnyk commented on .gitignore
> +backend/utils.js
since env is not in git we'll be on the safe side. but if leave this logic it means that doggy people can set env. JWT_SECRET to null and hack our security

2021-04-01 14:19 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +		if (user !== user) {
this will never be `true`. or what am I missing?

2021-04-01 14:19 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +			password: bcrypt.hashSync(req.body.password, 8),
what about this?

2021-04-01 14:19 UTC, MariiaKolisnyk commented on client/src/components/CheckoutSteps.js
> +			<div className={props.step4 ? "active" : ""}>Place Order</div>
could you change `step4` as well?

2021-04-02 13:44 UTC, MariiaKolisnyk approved these changes

2021-04-02 13:44 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +const productControllers = {
should be singular `productController`

2021-04-02 13:44 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +const userControllers = {
`userController`

2021-04-02 13:44 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		const userPosible = await User.findOne({ email: email });
I would say we should check at first and only then if there is no such an email call `new User`:
```
const isUserExist = await User.findOne({ email: email });
if (!isUserExist) {
  const user = new User({ ... });
  const createdUser = await user.save();
  return res.send({ ... });
} else {
  res.status(401).send({ message: "User Already exist" });
}
```

2021-04-02 14:00 UTC, merged